version: '3'
services:
  sample:
    build:
      context: .
      dockerfile: Dockerfile
    image: sample-app
    # environment:
    #   APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=**********"
